[package]
name = "caklimas-rust-gameboy"
version = "0.1.4"
authors = ["caklimas <caklimas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitfield = "0.13.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde-big-array = "0.3.0"
serde_json = "1.0.57"
wasm-bindgen = "0.2.63"