use super::cb_opcode::CbOpcode;
use super::opcode::{CpuRegister};

pub const CB_OPCODE_TABLE: [CbOpcode; 256] = [
             /* 0                                     1                                        2                                        3                                        4 	                                      5                                        6 	                      7                                        8                                        9                                        A                                        B                                        C                                        D                                        E                          F */
   /* 0 */   CbOpcode::RlcR8(CpuRegister::B),         CbOpcode::RlcR8(CpuRegister::C),         CbOpcode::RlcR8(CpuRegister::D),         CbOpcode::RlcR8(CpuRegister::E),         CbOpcode::RlcR8(CpuRegister::H),         CbOpcode::RlcR8(CpuRegister::L),         CbOpcode::RlcHl,           CbOpcode::RlcR8(CpuRegister::A),         CbOpcode::RrcR8(CpuRegister::B),         CbOpcode::RrcR8(CpuRegister::C),         CbOpcode::RrcR8(CpuRegister::D),         CbOpcode::RrcR8(CpuRegister::E),         CbOpcode::RrcR8(CpuRegister::H),         CbOpcode::RrcR8(CpuRegister::L),         CbOpcode::RrcHl,           CbOpcode::RrcR8(CpuRegister::A),
   /* 1 */   CbOpcode::RlR8(CpuRegister::B),          CbOpcode::RlR8(CpuRegister::C),          CbOpcode::RlR8(CpuRegister::D),          CbOpcode::RlR8(CpuRegister::E),          CbOpcode::RlR8(CpuRegister::H),          CbOpcode::RlR8(CpuRegister::L),          CbOpcode::RlHl,            CbOpcode::RlR8(CpuRegister::A),          CbOpcode::RrR8(CpuRegister::B),          CbOpcode::RrR8(CpuRegister::C),          CbOpcode::RrR8(CpuRegister::D),          CbOpcode::RrR8(CpuRegister::E),          CbOpcode::RrR8(CpuRegister::H),          CbOpcode::RrR8(CpuRegister::L),          CbOpcode::RrHl,            CbOpcode::RrR8(CpuRegister::A),
   /* 2 */   CbOpcode::SlaR8(CpuRegister::B),         CbOpcode::SlaR8(CpuRegister::C),         CbOpcode::SlaR8(CpuRegister::D),         CbOpcode::SlaR8(CpuRegister::E),         CbOpcode::SlaR8(CpuRegister::H),         CbOpcode::SlaR8(CpuRegister::L),         CbOpcode::SlaHl,           CbOpcode::SlaR8(CpuRegister::A),         CbOpcode::SraR8(CpuRegister::B),         CbOpcode::SraR8(CpuRegister::C),         CbOpcode::SraR8(CpuRegister::D),         CbOpcode::SraR8(CpuRegister::E),         CbOpcode::SraR8(CpuRegister::H),         CbOpcode::SraR8(CpuRegister::L),         CbOpcode::SraHl,           CbOpcode::SraR8(CpuRegister::A),
   /* 3 */   CbOpcode::SwapR8(CpuRegister::B),        CbOpcode::SwapR8(CpuRegister::C),        CbOpcode::SwapR8(CpuRegister::D),        CbOpcode::SwapR8(CpuRegister::E),        CbOpcode::SwapR8(CpuRegister::H),        CbOpcode::SwapR8(CpuRegister::L),        CbOpcode::SwapHl,          CbOpcode::SwapR8(CpuRegister::A),        CbOpcode::SrlR8(CpuRegister::B),         CbOpcode::SrlR8(CpuRegister::C),         CbOpcode::SrlR8(CpuRegister::D),         CbOpcode::SrlR8(CpuRegister::E),         CbOpcode::SrlR8(CpuRegister::H),         CbOpcode::SrlR8(CpuRegister::L),         CbOpcode::SrlHl,           CbOpcode::SrlR8(CpuRegister::A),
   /* 4 */   CbOpcode::BitNSetR8(CpuRegister::B, 0),  CbOpcode::BitNSetR8(CpuRegister::C, 0),  CbOpcode::BitNSetR8(CpuRegister::D, 0),  CbOpcode::BitNSetR8(CpuRegister::E, 0),  CbOpcode::BitNSetR8(CpuRegister::H, 0),  CbOpcode::BitNSetR8(CpuRegister::L, 0),  CbOpcode::BitNSetHl(0),    CbOpcode::BitNSetR8(CpuRegister::A, 0),  CbOpcode::BitNSetR8(CpuRegister::B, 1),  CbOpcode::BitNSetR8(CpuRegister::C, 1),  CbOpcode::BitNSetR8(CpuRegister::D, 1),  CbOpcode::BitNSetR8(CpuRegister::E, 1),  CbOpcode::BitNSetR8(CpuRegister::H, 1),  CbOpcode::BitNSetR8(CpuRegister::L, 1),  CbOpcode::BitNSetHl(1),    CbOpcode::BitNSetR8(CpuRegister::A, 1),
   /* 5 */   CbOpcode::BitNSetR8(CpuRegister::B, 2),  CbOpcode::BitNSetR8(CpuRegister::C, 2),  CbOpcode::BitNSetR8(CpuRegister::D, 2),  CbOpcode::BitNSetR8(CpuRegister::E, 2),  CbOpcode::BitNSetR8(CpuRegister::H, 2),  CbOpcode::BitNSetR8(CpuRegister::L, 2),  CbOpcode::BitNSetHl(2),    CbOpcode::BitNSetR8(CpuRegister::A, 2),  CbOpcode::BitNSetR8(CpuRegister::B, 3),  CbOpcode::BitNSetR8(CpuRegister::C, 3),  CbOpcode::BitNSetR8(CpuRegister::D, 3),  CbOpcode::BitNSetR8(CpuRegister::E, 3),  CbOpcode::BitNSetR8(CpuRegister::H, 3),  CbOpcode::BitNSetR8(CpuRegister::L, 3),  CbOpcode::BitNSetHl(3),    CbOpcode::BitNSetR8(CpuRegister::A, 3),
   /* 6 */   CbOpcode::BitNSetR8(CpuRegister::B, 4),  CbOpcode::BitNSetR8(CpuRegister::C, 4),  CbOpcode::BitNSetR8(CpuRegister::D, 4),  CbOpcode::BitNSetR8(CpuRegister::E, 4),  CbOpcode::BitNSetR8(CpuRegister::H, 4),  CbOpcode::BitNSetR8(CpuRegister::L, 4),  CbOpcode::BitNSetHl(4),    CbOpcode::BitNSetR8(CpuRegister::A, 4),  CbOpcode::BitNSetR8(CpuRegister::B, 5),  CbOpcode::BitNSetR8(CpuRegister::C, 5),  CbOpcode::BitNSetR8(CpuRegister::D, 5),  CbOpcode::BitNSetR8(CpuRegister::E, 5),  CbOpcode::BitNSetR8(CpuRegister::H, 5),  CbOpcode::BitNSetR8(CpuRegister::L, 5),  CbOpcode::BitNSetHl(5),    CbOpcode::BitNSetR8(CpuRegister::A, 5),
   /* 7 */   CbOpcode::BitNSetR8(CpuRegister::B, 6),  CbOpcode::BitNSetR8(CpuRegister::C, 6),  CbOpcode::BitNSetR8(CpuRegister::D, 6),  CbOpcode::BitNSetR8(CpuRegister::E, 6),  CbOpcode::BitNSetR8(CpuRegister::H, 6),  CbOpcode::BitNSetR8(CpuRegister::L, 6),  CbOpcode::BitNSetHl(6),    CbOpcode::BitNSetR8(CpuRegister::A, 6),  CbOpcode::BitNSetR8(CpuRegister::B, 7),  CbOpcode::BitNSetR8(CpuRegister::C, 7),  CbOpcode::BitNSetR8(CpuRegister::D, 7),  CbOpcode::BitNSetR8(CpuRegister::E, 7),  CbOpcode::BitNSetR8(CpuRegister::H, 7),  CbOpcode::BitNSetR8(CpuRegister::L, 7),  CbOpcode::BitNSetHl(7),    CbOpcode::BitNSetR8(CpuRegister::A, 7),
   /* 8 */   CbOpcode::ResR8(CpuRegister::B, 0),      CbOpcode::ResR8(CpuRegister::C, 0),      CbOpcode::ResR8(CpuRegister::D, 0),      CbOpcode::ResR8(CpuRegister::E, 0),      CbOpcode::ResR8(CpuRegister::H, 0),      CbOpcode::ResR8(CpuRegister::L, 0),      CbOpcode::ResHl(0),        CbOpcode::ResR8(CpuRegister::A, 0),      CbOpcode::ResR8(CpuRegister::B, 1),      CbOpcode::ResR8(CpuRegister::C, 1),      CbOpcode::ResR8(CpuRegister::D, 1),      CbOpcode::ResR8(CpuRegister::E, 1),      CbOpcode::ResR8(CpuRegister::H, 1),      CbOpcode::ResR8(CpuRegister::L, 1),      CbOpcode::ResHl(1),        CbOpcode::ResR8(CpuRegister::A, 1),
   /* 9 */   CbOpcode::ResR8(CpuRegister::B, 2),      CbOpcode::ResR8(CpuRegister::C, 2),      CbOpcode::ResR8(CpuRegister::D, 2),      CbOpcode::ResR8(CpuRegister::E, 2),      CbOpcode::ResR8(CpuRegister::H, 2),      CbOpcode::ResR8(CpuRegister::L, 2),      CbOpcode::ResHl(2),        CbOpcode::ResR8(CpuRegister::A, 2),      CbOpcode::ResR8(CpuRegister::B, 3),      CbOpcode::ResR8(CpuRegister::C, 3),      CbOpcode::ResR8(CpuRegister::D, 3),      CbOpcode::ResR8(CpuRegister::E, 3),      CbOpcode::ResR8(CpuRegister::H, 3),      CbOpcode::ResR8(CpuRegister::L, 3),      CbOpcode::ResHl(3),        CbOpcode::ResR8(CpuRegister::A, 3),
   /* A */   CbOpcode::ResR8(CpuRegister::B, 4),      CbOpcode::ResR8(CpuRegister::C, 4),      CbOpcode::ResR8(CpuRegister::D, 4),      CbOpcode::ResR8(CpuRegister::E, 4),      CbOpcode::ResR8(CpuRegister::H, 4),      CbOpcode::ResR8(CpuRegister::L, 4),      CbOpcode::ResHl(4),        CbOpcode::ResR8(CpuRegister::A, 4),      CbOpcode::ResR8(CpuRegister::B, 5),      CbOpcode::ResR8(CpuRegister::C, 5),      CbOpcode::ResR8(CpuRegister::D, 5),      CbOpcode::ResR8(CpuRegister::E, 5),      CbOpcode::ResR8(CpuRegister::H, 5),      CbOpcode::ResR8(CpuRegister::L, 5),      CbOpcode::ResHl(5),        CbOpcode::ResR8(CpuRegister::A, 5),
   /* B */   CbOpcode::ResR8(CpuRegister::B, 6),      CbOpcode::ResR8(CpuRegister::C, 6),      CbOpcode::ResR8(CpuRegister::D, 6),      CbOpcode::ResR8(CpuRegister::E, 6),      CbOpcode::ResR8(CpuRegister::H, 6),      CbOpcode::ResR8(CpuRegister::L, 6),      CbOpcode::ResHl(6),        CbOpcode::ResR8(CpuRegister::A, 6),      CbOpcode::ResR8(CpuRegister::B, 7),      CbOpcode::ResR8(CpuRegister::C, 7),      CbOpcode::ResR8(CpuRegister::D, 7),      CbOpcode::ResR8(CpuRegister::E, 7),      CbOpcode::ResR8(CpuRegister::H, 7),      CbOpcode::ResR8(CpuRegister::L, 7),      CbOpcode::ResHl(7),        CbOpcode::ResR8(CpuRegister::A, 7),
   /* C */   CbOpcode::SetR8(CpuRegister::B, 0),      CbOpcode::SetR8(CpuRegister::C, 0),      CbOpcode::SetR8(CpuRegister::D, 0),      CbOpcode::SetR8(CpuRegister::E, 0),      CbOpcode::SetR8(CpuRegister::H, 0),      CbOpcode::SetR8(CpuRegister::L, 0),      CbOpcode::SetHl(0),        CbOpcode::SetR8(CpuRegister::A, 0),      CbOpcode::SetR8(CpuRegister::B, 1),      CbOpcode::SetR8(CpuRegister::C, 1),      CbOpcode::SetR8(CpuRegister::D, 1),      CbOpcode::SetR8(CpuRegister::E, 1),      CbOpcode::SetR8(CpuRegister::H, 1),      CbOpcode::SetR8(CpuRegister::L, 1),      CbOpcode::SetHl(1),        CbOpcode::SetR8(CpuRegister::A, 1),
   /* D */   CbOpcode::SetR8(CpuRegister::B, 2),      CbOpcode::SetR8(CpuRegister::C, 2),      CbOpcode::SetR8(CpuRegister::D, 2),      CbOpcode::SetR8(CpuRegister::E, 2),      CbOpcode::SetR8(CpuRegister::H, 2),      CbOpcode::SetR8(CpuRegister::L, 2),      CbOpcode::SetHl(2),        CbOpcode::SetR8(CpuRegister::A, 2),      CbOpcode::SetR8(CpuRegister::B, 3),      CbOpcode::SetR8(CpuRegister::C, 3),      CbOpcode::SetR8(CpuRegister::D, 3),      CbOpcode::SetR8(CpuRegister::E, 3),      CbOpcode::SetR8(CpuRegister::H, 3),      CbOpcode::SetR8(CpuRegister::L, 3),      CbOpcode::SetHl(3),        CbOpcode::SetR8(CpuRegister::A, 3),
   /* E */   CbOpcode::SetR8(CpuRegister::B, 4),      CbOpcode::SetR8(CpuRegister::C, 4),      CbOpcode::SetR8(CpuRegister::D, 4),      CbOpcode::SetR8(CpuRegister::E, 4),      CbOpcode::SetR8(CpuRegister::H, 4),      CbOpcode::SetR8(CpuRegister::L, 4),      CbOpcode::SetHl(4),        CbOpcode::SetR8(CpuRegister::A, 4),      CbOpcode::SetR8(CpuRegister::B, 5),      CbOpcode::SetR8(CpuRegister::C, 5),      CbOpcode::SetR8(CpuRegister::D, 5),      CbOpcode::SetR8(CpuRegister::E, 5),      CbOpcode::SetR8(CpuRegister::H, 5),      CbOpcode::SetR8(CpuRegister::L, 5),      CbOpcode::SetHl(5),        CbOpcode::SetR8(CpuRegister::A, 5),
   /* F */   CbOpcode::SetR8(CpuRegister::B, 6),      CbOpcode::SetR8(CpuRegister::C, 6),      CbOpcode::SetR8(CpuRegister::D, 6),      CbOpcode::SetR8(CpuRegister::E, 6),      CbOpcode::SetR8(CpuRegister::H, 6),      CbOpcode::SetR8(CpuRegister::L, 6),      CbOpcode::SetHl(6),        CbOpcode::SetR8(CpuRegister::A, 6),      CbOpcode::SetR8(CpuRegister::B, 7),      CbOpcode::SetR8(CpuRegister::C, 7),      CbOpcode::SetR8(CpuRegister::D, 7),      CbOpcode::SetR8(CpuRegister::E, 7),      CbOpcode::SetR8(CpuRegister::H, 7),      CbOpcode::SetR8(CpuRegister::L, 7),      CbOpcode::SetHl(7),        CbOpcode::SetR8(CpuRegister::A, 7)
];