pub const WORK_RAM_FIXED_LOWER: u16 = 0xC000;
pub const WORK_RAM_FIXED_UPPER: u16 = 0xCFFF;
pub const WORK_RAM_SWITCHABLE_LOWER: u16 = 0xD000;
pub const WORK_RAM_SWITCHABLE_UPPER: u16 = 0xDFFF;
pub const WORK_RAM_ECHO_LOWER: u16 = 0xE000;
pub const WORK_RAM_ECHO_UPPER: u16 = 0xFDFF;