name: Deployment

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: wasm-pack build
    - run: rm pkg/caklimas_rust_gameboy.js
      continue-on-error: true
    - run: rm pkg/caklimas_rust_gameboy_bg.d.ts
      continue-on-error: true
    - run: mv pkg/caklimas_rust_gameboy_bg.js pkg/caklimas_rust_gameboy.js
    - name: Publish to npm
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ./pkg/package.json